### PR TITLE
Modernisation

### PR DESCRIPTION
**Pull request by CJKerr**
Create responsive layout. Live at https://cjkerr.github.io/powderworks.github.io/

### CODE REVIEW

**Comment by mauricerkelly** [comment]
This looks pretty awesome! 👍

**Review by mauricerkelly — APPROVED** [review]

**Comment by CJKerr** [comment]
Is @robmanthey away? This has been pending review for about a week now.

**Comment by mauricerkelly** [comment]
I'm guessing he's unavailable at the minute, but if he's just missed it, your mention might help.

**Comment by robmanthey** [comment]
Very nice work.  Published to the live site.

**Pull request merged**
