### PR TITLE
Add improved Powderworks logo

### PR DESCRIPTION
**Pull request by CJKerr**
Cleaner Powderworks logo. Based on the restored artwork made by ‎Jon
Mayers at
https://www.flickr.com/photos/129927139@N06/16763256855/in/album-72157650845578948/

We may wish to ask Jon's permission, but frankly it isn't his artwork to
begin with.

Logo desaturated, black point set to #111 to match page background,
feathered into transparency to ensure it looks good on any similar
background in future.

### CODE REVIEW

**Comment by mauricerkelly** [comment]
The file looks good, I'll pull this down tomorrow and have a look at it in situ, but this is pretty sweet, IMO!

**Review by robmanthey — APPROVED** [review]
Looks ok to me. Happy to act on the premise we already have the bands permission to use limited artwork since we have tacit permission via The Office to do this website in general.

**Review by mauricerkelly — APPROVED** [review]
👍

**Comment by robmanthey** [comment]
ftp'd to the live site

**Pull request merged**
